package com.yourdailyimprovement.androidapp.ui.theme

import androidx.compose.ui.graphics.Color

// --- Brand palette (green-forward, calm/minimal) ---------------------------

// Light scheme
val md_light_primary = Color(0xFF2E5E4E)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFB4F1D0)
val md_light_onPrimaryContainer = Color(0xFF00210F)
val md_light_secondary = Color(0xFF4E6355)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFD0E8D6)
val md_light_onSecondaryContainer = Color(0xFF0B1F14)
val md_light_tertiary = Color(0xFF3D6373)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFC1E8FB)
val md_light_onTertiaryContainer = Color(0xFF001F29)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFF6FBF6)
val md_light_onBackground = Color(0xFF191C1A)
val md_light_surface = Color(0xFFF6FBF6)
val md_light_onSurface = Color(0xFF191C1A)
val md_light_surfaceVariant = Color(0xFFDBE5DC)
val md_light_onSurfaceVariant = Color(0xFF404942)
val md_light_outline = Color(0xFF707972)
val md_light_outlineVariant = Color(0xFFBFC9C0)

// Dark scheme
val md_dark_primary = Color(0xFF98D8B5)
val md_dark_onPrimary = Color(0xFF003823)
val md_dark_primaryContainer = Color(0xFF145236)
val md_dark_onPrimaryContainer = Color(0xFFB4F1D0)
val md_dark_secondary = Color(0xFFB4CCBA)
val md_dark_onSecondary = Color(0xFF203528)
val md_dark_secondaryContainer = Color(0xFF364B3E)
val md_dark_onSecondaryContainer = Color(0xFFD0E8D6)
val md_dark_tertiary = Color(0xFFA5CCDF)
val md_dark_onTertiary = Color(0xFF063543)
val md_dark_tertiaryContainer = Color(0xFF234C5B)
val md_dark_onTertiaryContainer = Color(0xFFC1E8FB)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF191C1A)
val md_dark_onBackground = Color(0xFFE1E3DE)
val md_dark_surface = Color(0xFF191C1A)
val md_dark_onSurface = Color(0xFFE1E3DE)
val md_dark_surfaceVariant = Color(0xFF404942)
val md_dark_onSurfaceVariant = Color(0xFFBFC9C0)
val md_dark_outline = Color(0xFF8A938B)
val md_dark_outlineVariant = Color(0xFF404942)
